# Uncomment the next line to define a global platform for your project
platform :ios, '13.2'

target 'BasicVoiceApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'speeblyclientsdk', '0.1.6', :source => "https://github.com/speebly/ios-client-framework-podspec.git"
  pod 'SwiftGRPC'

  # Pods for BasicVoiceApp

end
